music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # / Music /
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # Music/Album/Add
    url(r' album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # Music/Album/#/update
    url(r'^(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-updae'),

    # Music/Album/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumCreate.as_view(), name='album-delete')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from website import music

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

music/models.py
from django.db import models
from django.core.urlresolvers import  reverse
# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from .models import Album
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = "music/index.html"
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add Forms title goes here {% endblock %}
{% block albums_active %} active {% endblock %}
{% block body %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizotal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Music App {% endblock%}</title>
</head>
<body>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        <!-- Nav Bar -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'music:index' %}">Music App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse dual-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Albums</a>
                    </li>
        
                    <li class="nav-item">
                        <a class="nav-link" href="#">Songs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                </ul>
                <form class=" form-inline" role="search" method="get" action="">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q" aria-label="Search">
                        <button class="btn btn-default my-2 my-sm-0" type="submit">Search</button>
                    </form>
            </div>
            <div class="navbar-collapse collapse dual-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'music:album-add' %}">Add Album</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Nav Bar End -->

        {% block body %}
        {% endblock %}
    
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Music Details Page {% endblock%}
{% block body %}
<img src=" {{ album.album_logo }} "/>

    <h1> {{ album.album_title }}</h1>
    <h3> {{ album.artist }} </h3>

    {% if error_message %}
        <p><strong> {{ error_message }} </strong></p>
    {% endif %}

    <form action="{% url 'music:favourite' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id=" song{{ forloop.counter}}" name="song" value="{{song.id}}">
            <label for="song{{ forloop.counter }}">

                {{ song.song_title }}
                {% if song.is_favourite %}
                    <img src="http://i.imgur.com/b9b13Rd.png"/>
                {% endif %}
            </label><br>
        {% endfor %}
            <input type="submit" value="Favorite">
    </form>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">
                {{ field.error }}
            </span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

    </div>

{% endfor %}

music/templates/music/index.html
<!-- Loads the path to the static files -->
{% extends "music/base.html" %}
{% block title %} Music Landing Page {% endblock%}
{% block body %}


    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a> </li>
        {% endfor %}
    </ul>


{% endblock %}